import { Config } from "../src/types";
import { venueInfo } from "./venues";

const config: Config = {
  maxSols: 1,
  maxDist: -1,
  prefDays: [],
  breaks: [
    {
      minDuration: 60,
      timeslots: [
        {
          start: 1100,
          end: 1200,
        },
      ],
    },
  ],
  venueInfo,
};

const index = 0;

const input = [
  [
    {
      classNo: "2",
      startTime: "1600",
      endTime: "1800",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
      venue: "LT27",
      day: "Thursday",
      lessonType: "Lecture",
      size: 500,
      covidZone: "B",
      moduleCode: "ST2334",
      title: "Probability and Statistics",
    },
    {
      classNo: "1",
      startTime: "1200",
      endTime: "1400",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
      venue: "LT9",
      day: "Thursday",
      lessonType: "Lecture",
      size: 240,
      covidZone: "B",
      moduleCode: "CS3235",
      title: "Computer Security",
    },
    {
      classNo: "Z1",
      startTime: "1000",
      endTime: "1200",
      weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
      venue: "LT17",
      day: "Thursday",
      lessonType: "Lecture",
      size: 120,
      covidZone: "B",
      moduleCode: "MNO1706X",
      title: "Organisational Behaviour",
    },
    {
      classNo: "Z02",
      startTime: "1300",
      endTime: "1500",
      weeks: [2, 4, 6, 8, 10, 12],
      venue: "BIZ2-0118",
      day: "Thursday",
      lessonType: "Tutorial",
      size: 50,
      covidZone: "B",
      moduleCode: "MNO1706X",
      title: "Organisational Behaviour",
    },
    {
      classNo: "Z03",
      startTime: "1500",
      endTime: "1700",
      weeks: [1, 3, 5, 7, 9, 11, 13],
      venue: "BIZ2-0118",
      day: "Thursday",
      lessonType: "Tutorial",
      size: 50,
      covidZone: "B",
      moduleCode: "MNO1706X",
      title: "Organisational Behaviour",
    },
    {
      classNo: "Z04",
      startTime: "1500",
      endTime: "1700",
      weeks: [2, 4, 6, 8, 10, 12],
      venue: "BIZ2-0118",
      day: "Thursday",
      lessonType: "Tutorial",
      size: 50,
      covidZone: "B",
      moduleCode: "MNO1706X",
      title: "Organisational Behaviour",
    },
    {
      classNo: "Z01",
      startTime: "1300",
      endTime: "1500",
      weeks: [1, 3, 5, 7, 9, 11, 13],
      venue: "BIZ2-0118",
      day: "Thursday",
      lessonType: "Tutorial",
      size: 50,
      covidZone: "B",
      moduleCode: "MNO1706X",
      title: "Organisational Behaviour",
    },
  ],
];

const output = [
  {
    classNo: "2",
    startTime: "1600",
    endTime: "1800",
    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    venue: "LT27",
    day: "Thursday",
    lessonType: "Lecture",
    size: 500,
    covidZone: "B",
    moduleCode: "ST2334",
    title: "Probability and Statistics",
  },
  {
    classNo: "1",
    startTime: "1200",
    endTime: "1400",
    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    venue: "LT9",
    day: "Thursday",
    lessonType: "Lecture",
    size: 240,
    covidZone: "B",
    moduleCode: "CS3235",
    title: "Computer Security",
  },
  {
    classNo: "Z1",
    startTime: "1000",
    endTime: "1200",
    weeks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    venue: "LT17",
    day: "Thursday",
    lessonType: "Lecture",
    size: 120,
    covidZone: "B",
    moduleCode: "MNO1706X",
    title: "Organisational Behaviour",
  },
];

export { input, config, output, index };
